run_mode: kSim
trigger_mode: kManual
init_motion_enable: false
planner_trigger_lead_time: 0.1
smooth_heading_enable: true
init_motion:
  z_takeoff: 3.0
  z_drop: 0.5
  x_forward: 3.5

# Group related parameters to be shared between nodes.
RobotDynamics:
  # v_max: 1.0
  v_init_max: 1.5
  v_homing_max: 1.0
  yaw_rate_max: 0.3
  dt: 0.05